# Generated by Django 4.1.1 on 2022-09-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_contact', models.CharField(max_length=100)),
                ('sender', models.CharField(max_length=50, verbose_name='Отправитель')),
                ('message', models.TextField(verbose_name='Текст сообщения')),
                ('date_time', models.DateTimeField(verbose_name='Дата отправки')),
            ],
        ),
    ]
