# Generated by Django 4.1.1 on 2022-09-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='date_time',
            field=models.CharField(max_length=50, verbose_name='Дата отправки'),
        ),
    ]
