# Generated by Django 4.1.1 on 2022-10-01 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_messages_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='date_time',
        ),
    ]
