# Generated by Django 4.1.1 on 2022-10-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_messages_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='sender',
            field=models.TextField(verbose_name='Отправитель'),
        ),
    ]
